# Generated by Django 5.2.3 on 2025-06-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
