# Generated by Django 5.2.3 on 2025-06-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_loans_amount_alter_loans_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentcategory',
            name='category_name',
            field=models.CharField(choices=[('Stocks', 'Stocks'), ('Bonds', 'Bonds'), ('Real Estate', 'Real Estate'), ('Mutual Funds', 'Mutual Funds'), ('Cryptocurrency', 'Cryptocurrency'), ('Commodities', 'Commodities'), ('Exchange-Traded Funds (ETFs)', 'Exchange-Traded Funds (ETFs)'), ('Index Funds', 'Index Funds'), ('Options', 'Options'), ('Forex', 'Forex'), ('Peer-to-Peer Lending', 'Peer-to-Peer Lending'), ('Crowdfunding', 'Crowdfunding'), ('Retirement Accounts', 'Retirement Accounts'), ('Savings Accounts', 'Savings Accounts'), ('Certificates of Deposit (CDs)', 'Certificates of Deposit (CDs)'), ('Treasury Securities', 'Treasury Securities'), ('Annuities', 'Annuities'), ('Precious Metals', 'Precious Metals'), ('Collectibles', 'Collectibles'), ('Other', 'Other')], default='Bonds', max_length=100),
        ),
    ]
