# Generated by Django 5.2.3 on 2025-06-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_networth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networth',
            name='date',
            field=models.DateField(),
        ),
    ]
